# fly.toml app configuration file generated for duthweatherstation on 2024-05-25T17:15:21+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'duthweatherstation'
primary_region = 'otp'

[build]

[env]
  DB_DATABASE = 'weather_station'
  DB_HOST = 'duthweatherstation.mysql.database.azure.com'
  DB_PASSWORD = 'pA6#asd5Gzdw*VB'
  DB_PORT = '3306'
  DB_ROOT_PASSWORD = 'pA6#asd5Gzdw*VB'
  DB_USERNAME = 'petrside'
  PORT = '443'

[http_service]
  internal_port = 443
  force_https = true
  auto_stop_machines = false
  min_machines_running = 2
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
